logging:
  level:
    root: WARN
    org.springframework.boot: INFO

spring:
  jpa:
    generate-ddl: true
    show-sql: true
  output:
    ansi:
      enabled: always
  logging:
    pattern:
      dateformat: "yyyy-MM-dd HH:mm:ss"

server:
  address: 0.0.0.0

app:
  welcome-message: "Welcome to Spring blog!"
